#FROM jupyter/tensorflow-notebook:tensorflow-2.4.1
FROM tensorflow/tensorflow:latest-gpu-jupyter

#RUN pip install tqdm
#RUN pip install plotly
#RUN pip install tensorflow
#RUN conda install py-xgboost